#!/bin/bash -l
#PBS -l walltime=8:00:00,nodes=1:ppn=5,pmem=8gb
#PBS -m abe
#PBS -M chen7090@umn.edu

module load python3/3.8.3_anaconda2020.07_mamba
module load intel 
module load ompi/intel 

echo "module loaded"
folder_str='./datafiles_'
dt_str=$(date +'%Y%m%d-%H%M')
folder_name="${folder_str}${dt_str}"
mpirun -np 10 python3 run_multiprocessing.py
echo $folder_name
mkdir $folder_name
mv dataset* $folder_name

